# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_design.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 558)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(267, 390))
        self.groupBox.setMaximumSize(QtCore.QSize(267, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_16.addWidget(self.label)
        self.cmbStyle = QtWidgets.QComboBox(self.groupBox)
        self.cmbStyle.setObjectName("cmbStyle")
        self.cmbStyle.addItem("")
        self.cmbStyle.addItem("")
        self.cmbStyle.addItem("")
        self.verticalLayout_16.addWidget(self.cmbStyle)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_14.addWidget(self.label_12)
        self.horizontalLayout_11.addLayout(self.verticalLayout_14)
        self.dial_3 = QtWidgets.QDial(self.groupBox)
        self.dial_3.setMinimum(1)
        self.dial_3.setMaximum(4)
        self.dial_3.setPageStep(1)
        self.dial_3.setProperty("value", 3)
        self.dial_3.setObjectName("dial_3")
        self.horizontalLayout_11.addWidget(self.dial_3)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_15.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_15.addWidget(self.label_14)
        self.horizontalLayout_11.addLayout(self.verticalLayout_15)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btnSave = QtWidgets.QPushButton(self.groupBox)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_12.addWidget(self.btnSave)
        self.btnUndo_3 = QtWidgets.QPushButton(self.groupBox)
        self.btnUndo_3.setMouseTracking(False)
        self.btnUndo_3.setCheckable(False)
        self.btnUndo_3.setObjectName("btnUndo_3")
        self.horizontalLayout_12.addWidget(self.btnUndo_3)
        self.btnBrowse_3 = QtWidgets.QPushButton(self.groupBox)
        self.btnBrowse_3.setObjectName("btnBrowse_3")
        self.horizontalLayout_12.addWidget(self.btnBrowse_3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.verticalLayout_16.addLayout(self.verticalLayout_13)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(25, 20))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btnPrevFrame = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPrevFrame.sizePolicy().hasHeightForWidth())
        self.btnPrevFrame.setSizePolicy(sizePolicy)
        self.btnPrevFrame.setMinimumSize(QtCore.QSize(25, 25))
        self.btnPrevFrame.setMaximumSize(QtCore.QSize(25, 25))
        self.btnPrevFrame.setAutoFillBackground(False)
        self.btnPrevFrame.setText("")
        self.btnPrevFrame.setObjectName("btnPrevFrame")
        self.horizontalLayout_14.addWidget(self.btnPrevFrame)
        self.btnPlay = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPlay.sizePolicy().hasHeightForWidth())
        self.btnPlay.setSizePolicy(sizePolicy)
        self.btnPlay.setMinimumSize(QtCore.QSize(25, 25))
        self.btnPlay.setMaximumSize(QtCore.QSize(25, 25))
        self.btnPlay.setText("")
        self.btnPlay.setObjectName("btnPlay")
        self.horizontalLayout_14.addWidget(self.btnPlay)
        self.btnNextFrame = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNextFrame.sizePolicy().hasHeightForWidth())
        self.btnNextFrame.setSizePolicy(sizePolicy)
        self.btnNextFrame.setMinimumSize(QtCore.QSize(25, 25))
        self.btnNextFrame.setMaximumSize(QtCore.QSize(25, 25))
        self.btnNextFrame.setText("")
        self.btnNextFrame.setObjectName("btnNextFrame")
        self.horizontalLayout_14.addWidget(self.btnNextFrame)
        self.videoSlider = QtWidgets.QSlider(self.groupBox_4)
        self.videoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.videoSlider.setObjectName("videoSlider")
        self.horizontalLayout_14.addWidget(self.videoSlider)
        self.verticalLayout_16.addWidget(self.groupBox_4)
        self.horizontalLayout_10.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(431, 391))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.wgt_player = QVideoWidget(self.groupBox_3)
        self.wgt_player.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.wgt_player.setMouseTracking(False)
        self.wgt_player.setObjectName("wgt_player")
        self.verticalLayout_12.addWidget(self.wgt_player)
        self.horizontalLayout_10.addWidget(self.groupBox_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 120))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setReadOnly(True)
        self.textEdit.setOverwriteMode(False)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_11.addWidget(self.textEdit)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 724, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionVideo_Analysis = QtWidgets.QAction(MainWindow)
        self.actionVideo_Analysis.setObjectName("actionVideo_Analysis")
        self.actionPaws_Analysis = QtWidgets.QAction(MainWindow)
        self.actionPaws_Analysis.setObjectName("actionPaws_Analysis")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_as)
        self.menuAbout.addAction(self.actionAbout)
        self.menuSettings.addAction(self.actionVideo_Analysis)
        self.menuSettings.addAction(self.actionPaws_Analysis)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rat Paws Detection"))
        self.groupBox.setTitle(_translate("MainWindow", "Панель управления"))
        self.label.setText(_translate("MainWindow", "Стиль:"))
        self.cmbStyle.setItemText(0, _translate("MainWindow", "windowsvista"))
        self.cmbStyle.setItemText(1, _translate("MainWindow", "Windows"))
        self.cmbStyle.setItemText(2, _translate("MainWindow", "Fusion"))
        self.label_11.setText(_translate("MainWindow", "Левая передняя"))
        self.label_12.setText(_translate("MainWindow", "Левая задняя"))
        self.label_13.setText(_translate("MainWindow", "Правая передняя"))
        self.label_14.setText(_translate("MainWindow", "Правая задняя"))
        self.btnSave.setText(_translate("MainWindow", "Извлечь"))
        self.btnUndo_3.setText(_translate("MainWindow", "Очистить"))
        self.btnBrowse_3.setText(_translate("MainWindow", "Выбрать файл"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Проигрыватель"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Область видоса"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Log"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "Info"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionVideo_Analysis.setText(_translate("MainWindow", "Video Analysis"))
        self.actionPaws_Analysis.setText(_translate("MainWindow", "Paws Analysis"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
